name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step to check out the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your requirements file is in the root or adjust the path

      # Add the following step to list the Travel directory
      - name: List Travel directory
        run: ls -R Travel

      # Your existing steps to run tests or start the application
      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Adjust if you are using a different test framework

      # Step to upload artifacts (if applicable)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            Travel/Admin
            Travel/User
            Travel/templates
